name: interact
description: A collection of customizable interactive command-line components.
version: 2.2.0
repository: https://github.com/frencojobs/interact

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_console: ^1.1.2
  meta: ^1.8.0
  tint: ^2.0.0

dev_dependencies:
  lint: ^2.0.1
  test: ^1.22.2
